import { RiftIcon } from "../components/rift/RiftIcon";
import { ENQUIRY_LINKS } from "../lib/enquiry-config";
import { sectors } from "../lib/capital-data";
import { Link } from "react-router-dom";
export const Businesses = () => <main id="main" className="r-business">
  <header className="r-biz-hero"><div className="r-shell"><h1>Capital for your next stage of growth.</h1><p className="r-biz-hero-lead">Tell us what your business needs to grow. Rift is developing financing opportunities across trade, energy, agriculture and the wider productive economy.</p><div className="r-biz-hero-cta"><a className="r-button r-button-primary" href={ENQUIRY_LINKS.financing}>Request financing <RiftIcon name="arrow" /></a><a className="r-button r-button-outline" href="#business-sectors">Explore our sectors <RiftIcon name="arrow" /></a></div></div></header>
  <section className="r-section"><div className="r-shell r-vision-grid"><h2>Start with what your business is owed.</h2><div><p>Our first product focuses on financing against verified, short-term receivables for remittance and FX businesses. An approved advance can bridge the wait for an eligible settlement payment.</p><p>Accepted invoices in trade, agriculture and energy may support future facilities. Equipment and new projects require different structures and assessment.</p><Link className="r-link" to="/how-it-works">Explore how financing works <RiftIcon name="arrow" /></Link></div></div></section>
  <section className="r-sectors r-section" id="business-sectors"><div className="r-shell"><h2>Across the productive economy.</h2><div className="r-sector-grid">{sectors.map(s => <article key={s.id}><RiftIcon name={s.icon} /><h3>{s.name}</h3><p>{s.description}</p></article>)}</div></div></section>
  <section className="r-contact"><div className="r-shell"><h2>Discuss your financing needs.</h2><p style={{maxWidth:680,marginBottom:28}}>Financing products are still being structured. An enquiry starts a conversation; it does not guarantee funding. Any facility will depend on assessment, eligibility and a separate financing agreement.</p><a className="r-button r-button-primary" href={ENQUIRY_LINKS.financing}>Start an enquiry <RiftIcon name="arrow" /></a></div></section>
</main>;
