import { RiftIcon } from "../components/rift/RiftIcon";
import { ENQUIRY_LINKS } from "../lib/enquiry-config";
import { sectors } from "../lib/capital-data";
import { Link } from "react-router-dom";
export const Businesses = () => <main id="main" className="r-business">
  <header className="r-biz-hero"><div className="r-shell"><h1>Keep payouts moving. Bridge the settlement gap.</h1><p className="r-biz-hero-lead">Settlement liquidity for remittance companies, cross-border payment apps and payment service providers. Bring forward funds owed by your processors and settlement partners.</p><div className="r-biz-hero-cta"><a className="r-button r-button-primary" href={ENQUIRY_LINKS.financing}>Request settlement liquidity <RiftIcon name="arrow" /></a><a className="r-button r-button-outline" href="#business-sectors">Future opportunities <RiftIcon name="arrow" /></a></div></div></header>
  <section className="r-section"><div className="r-shell r-vision-grid"><h2>Start with what your business is owed.</h2><div><p>Your customer needs a payout before your settlement partner pays you. Rift verifies the receivable, agrees the collection route and financing terms, and provides an approved USDC advance. The incoming settlement repays the facility.</p><p>USDC funding can move around the clock, with transfers settling in seconds on supported networks. Conversion and the final local-currency payout depend on your payout partners.</p><Link className="r-link" to="/how-it-works">Explore how financing works <RiftIcon name="arrow" /></Link></div></div></section>
  <section className="r-sectors r-section" id="business-sectors"><div className="r-shell"><h2>Other sectors. Future possibilities.</h2><p>We are exploring receivables financing beyond payments. Express interest to discuss a future facility for your sector.</p><div className="r-sector-grid">{sectors.filter(s => s.id !== "trade").map(s => <article key={s.id}><RiftIcon name={s.icon} /><h3>{s.name}</h3><p>{s.description}</p></article>)}</div></div></section>
  <section className="r-contact"><div className="r-shell"><h2>Discuss your financing needs.</h2><p style={{maxWidth:680,marginBottom:28}}>Financing products are still being structured. An enquiry starts a conversation; it does not guarantee funding. Any facility will depend on assessment, eligibility and a separate financing agreement.</p><a className="r-button r-button-primary" href={ENQUIRY_LINKS.financing}>Start an enquiry <RiftIcon name="arrow" /></a></div></section>
</main>;
