import { RiftIcon } from "../components/rift/RiftIcon";
import { ENQUIRY_LINKS } from "../lib/enquiry-config";
import { Link } from "react-router-dom";

const ELIGIBLE = ["The transaction has already occurred.", "The counterparty obligation is established.", "The amount is known.", "The payer is creditworthy.", "The settlement date is predictable.", "The cash has not arrived yet."];

export const Businesses = () => <main id="main" className="r-business">
  <header className="r-biz-hero"><div className="r-shell"><h1>Keep payouts moving. Bridge the settlement gap.</h1><p className="r-biz-hero-lead">Settlement liquidity for remittance companies, cross-border payment apps, payment service providers, FX businesses and merchants settling through a PSP. Bring forward funds your processors and settlement partners already owe you.</p><div className="r-biz-hero-cta"><a className="r-button r-button-primary" href={ENQUIRY_LINKS.financing}>Request settlement liquidity <RiftIcon name="arrow" /></a><a className="r-button r-button-outline" href="#eligibility">What makes a receivable eligible <RiftIcon name="arrow" /></a></div></div></header>
  <section className="r-section" id="timing"><div className="r-shell r-vision-grid"><h2>The payout is due before the money lands.</h2><div><p>Payment companies frequently face timing mismatches between when a transaction must be paid out and when the underlying funds become available through processors, acquirers, banks or settlement partners. This can force them to hold prefunded liquidity across payment corridors.</p><p>Card settlements commonly become available to the payment company several days after the transaction, while local bank-transfer and instant rails are typically faster. Aggregator-to-merchant settlement often runs on a fixed schedule agreed between the parties, and published industry ranges of roughly one to thirty days exist depending on the method and the country.</p><p>Rift advances against the settlement you are already owed. We verify the receivable, agree the collection route and the financing terms, and fund an approved advance in USDC. The incoming settlement repays the advance and the agreed financing charge.</p><Link className="r-link" to="/how-it-works">Explore how financing works <RiftIcon name="arrow" /></Link></div></div></section>
  <section className="r-example r-biz-band" id="layers"><div className="r-shell"><div className="r-biz-head-2col" style={{ marginBottom: 45 }}><h2>Two financeable layers.</h2><p>The same settlement chain holds two distinct obligations. Either can be the asset behind an advance, provided the obligation is established, assignable and controllable.</p></div><div className="r-biz-segs"><div className="r-biz-seg"><RiftIcon name="institution" /><div><strong>Layer A. Owed to the payment company</strong><p>The processor, acquirer or collection entity owes the payment company for transactions that have already occurred. The payment company needs that money before the settlement window closes.</p></div></div><div className="r-biz-seg"><RiftIcon name="trade" /><div><strong>Layer B. Owed to the merchant</strong><p>The payment service provider or aggregator owes its merchant. The merchant’s claim on its PSP balance is itself a financeable receivable while it waits for the scheduled payout.</p></div></div></div></div></section>
  <section className="r-section" id="eligibility"><div className="r-shell r-vision-grid"><h2>We underwrite the receivable, not the forecast.</h2><div className="r-audience-copy"><p>The question is not whether a business will survive the next year. It is whether this receivable is genuine, who owes it, whether it can be assigned and controlled, when it settles, and what the historical failure and reversal rate looks like on that flow.</p><ul>{ELIGIBLE.map(item => <li key={item}><RiftIcon name="check" /><span>{item}</span></li>)}</ul></div></div></section>
  <section className="r-section" id="usdc"><div className="r-shell r-vision-grid"><h2>Funded in USDC, repaid from settlement.</h2><div><p>Approved advances are funded in USDC. Transfers can settle in seconds on supported networks and move around the clock, which is useful when a payout window does not follow banking hours.</p><p>Approval, network finality, conversion and the final local-currency payout have their own timings and depend on your own payment partners. Smart contracts record and route the funds they receive; they cannot force a payer to pay.</p></div></div></section>
  <section className="r-contact"><div className="r-shell"><h2>Discuss your financing needs.</h2><p style={{ maxWidth: 680, marginBottom: 28 }}>Financing and investment products are in preparation. Enquiries are open. An enquiry starts a conversation; it is not an offer, an allocation, an approval or a commitment, and it does not guarantee funding. Any facility will depend on assessment, eligibility and a separate financing agreement.</p><a className="r-button r-button-primary" href={ENQUIRY_LINKS.financing}>Start an enquiry <RiftIcon name="arrow" /></a><p className="r-disclosure">Tell us your operating markets, the settlement partners you collect from, your typical settlement window and the liquidity you need.</p></div></section>
</main>;
