import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CapitalNav, CapitalFooter } from '../components/rift/CapitalChrome';
import { RiftIcon } from '../components/rift/RiftIcon';
import { FxLiquidity } from '../components/rift/FxLiquidity';
import { ENQUIRY_LINKS as links } from '../lib/enquiry-config';
import '../styles/capital.scss';
import '../styles/receivables-home.scss';
const PHOTO_ALT = 'Illustrative view of a container port handling cross-border trade';
const items = [
  { name: 'Remittance companies', title: 'Pay out today. Settle in days.', text: 'The corridor payout is due the moment a customer sends. The funds owed to you by your bank, processor or settlement partner arrive later, on their own cycle. Rift advances USDC against that established claim, so the corridor keeps running on less prefunded cash.', asset: 'A verified settlement claim on your partner', repayment: 'The partner settlement, on its scheduled date', image: 'port' },
  { name: 'Cross-border payment apps', title: 'Collections clear later than payouts.', text: 'Money is collected on one rail and paid out on another, and the two rarely settle on the same clock. Financing against a verified incoming settlement covers that gap, instead of parking prefunded balances in every corridor you serve.', asset: 'Established claims on processors, acquirers and collection partners', repayment: 'The incoming settlement, collected through an agreed route', image: 'port' },
  { name: 'Payment service providers', title: 'Two obligations. Both financeable.', text: 'A processor or acquirer owes you on its settlement cycle, and you owe your merchants on yours. Card settlements commonly become available several days after the transaction; local transfer rails are typically faster. Both obligations carry a named payer and a known date.', asset: 'Processor and acquirer receivables, and merchant claims on PSP balances', repayment: 'Processor or partner payment, on the agreed settlement date', image: 'port' },
];
const Arrow = () => <RiftIcon name="arrow" />;
export const Home = () => {
  const [active, setActive] = useState(0);
  const item = items[active];
  function select(index: number, focus = false) { const next = (index + items.length) % items.length; setActive(next); if (focus) document.getElementById(`receivable-tab-${next}`)?.focus(); }
  return <div className="rift-site rift-home-v2"><CapitalNav /><main id="main">
    <section className="rh-hero"><div className="r-shell rh-hero-heading"><h1>Stablecoin liquidity.<br /><span>Before settlement arrives.</span></h1><div><p>You are owed money that clears in days. Rift advances it in seconds. Stablecoins move faster and cost less than correspondent banking, so your payout goes out now instead of at the end of the cycle. The incoming settlement repays the advance.</p><div className="r-actions"><a className="r-button r-button-primary" href={links.financing}>Request settlement liquidity <Arrow /></a><a className="r-link" href="#invest">Invest with Rift <Arrow /></a></div></div></div>
    <div className="r-shell rh-carousel" role="region" aria-roledescription="carousel" aria-label="Payment businesses we serve"><div className="rh-tabs" role="tablist" aria-label="Explore payment businesses">{items.map((slide,i) => <button key={slide.name} id={`receivable-tab-${i}`} role="tab" aria-selected={active === i} aria-controls="receivable-panel" tabIndex={active === i ? 0 : -1} onClick={() => select(i)} onKeyDown={e => { if (['ArrowRight','ArrowLeft','Home','End'].includes(e.key)) { e.preventDefault(); select(e.key === 'Home' ? 0 : e.key === 'End' ? 2 : i + (e.key === 'ArrowRight' ? 1 : -1), true); } }}><span>{slide.name}</span><Arrow /></button>)}</div>
    <div className="rh-slide" id="receivable-panel" role="tabpanel" aria-labelledby={`receivable-tab-${active}`} tabIndex={0}><div className="rh-slide-photo"><img key={active} src={`/brand/receivables-${item.image}.png`} alt={PHOTO_ALT} width="1536" height="1024" fetchPriority="high" /><div className="rh-photo-caption"><span>Illustrative</span><span>{String(active+1).padStart(2,'0')} / 03</span></div></div><div className="rh-slide-copy" aria-live="polite"><div><h2>{item.title}</h2><p>{item.text}</p></div><dl><div><dt>What backs the financing</dt><dd>{item.asset}</dd></div><div><dt>Where repayment comes from</dt><dd>{item.repayment}</dd></div></dl><div className="rh-slide-bottom"><a className="r-link" href={links.financing}>Discuss settlement liquidity <Arrow /></a><div className="rh-controls"><button aria-label="Previous receivable" onClick={() => select(active-1)}><Arrow /></button><button aria-label="Next receivable" onClick={() => select(active+1)}><Arrow /></button></div></div></div></div><p className="rh-availability">Financing and investment products are in preparation. Enquiries are open.</p></div></section>
    <FxLiquidity />
    <section className="rh-intro r-shell" id="vision"><h2>Your customers move fast.<br />Your liquidity should too.</h2><div><p>A customer needs paying today. Your processor, acquirer or bank settles in a few days. Most providers bridge that with prefunded cash parked in every corridor, sized for the worst day it might see.</p><p>Rift bridges it with an approved USDC advance against the verified claim. The money moves on rails we operate, the payout leg settles on-chain wherever a local stablecoin or tokenized deposit exists, and the incoming settlement repays the advance and its financing charge.</p><Link className="r-link" to="/how-it-works">See how Rift works <Arrow /></Link></div></section>
    <section className="rh-flow" id="how-it-works"><div className="r-shell"><div className="rh-section-heading"><h2>A clear path from<br />receivable to capital.</h2><Link className="r-link" to="/how-it-works">Explore the process <Arrow /></Link></div><div className="rh-flow-grid">{[
      ['Show what you’re owed.','Share your settlement records, payer and expected payment date. We verify the incoming obligation and agree collection terms.'],
      ['Bring your capital forward.','Agree your facility and receive an advance against eligible receivables. Put it to work where your business needs it.'],
      ['Repay as payments arrive.','Collections follow an agreed route to repay the advance and interest. A clear connection between financing and its repayment source.'],
    ].map(([title,text],i) => <article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="rh-invest r-shell" id="invest"><div><h2>Your capital.<br />Connected to<br />real business.</h2><p>Supply liquidity to payment companies against verified settlement receivables. They pay a financing charge for earlier access to funds. Income is distributed only as it is collected, under each pool’s terms, after fees, expenses and losses.</p><Link className="r-link" to="/how-it-works#investor-income">Understand how you earn <Arrow /></Link><p className="rh-availability">Financing and investment products are in preparation. Enquiries are open. Capital is at risk and no return is guaranteed or projected.</p></div><div className="rh-invest-options"><article><RiftIcon name="wallet" /><h3>For individuals</h3><p>Explore Rift Wallet, your access point for future investment opportunities.</p><a className="r-link" href="https://wallet.riftfi.com">Explore the wallet <Arrow /></a></article><article><RiftIcon name="institution" /><h3>For institutions</h3><p>Discuss allocations, investment duration and the receivables that fit your mandate.</p><a className="r-link" href={links.investor}>Talk to our team <Arrow /></a></article></div></section>
    <section className="rh-asset" id="what-we-finance"><div className="r-shell"><div className="rh-section-heading"><h2>What we finance.<br />And what we check.</h2><p>Rift advances against settlement obligations that already exist. Two layers of the payment chain qualify.</p></div><div className="rh-layers">{[
      ['Layer A','The processor owes the payment company','A processor, acquirer, bank or collection entity holds funds due to the payment company and releases them on a settlement cycle. Card settlements commonly become available several days after the transaction; local bank-transfer and instant rails are typically faster.'],
      ['Layer B','The payment company owes its merchant','A PSP or aggregator settles merchant balances on a fixed schedule, commonly configurable by agreement, with published periods that can range from a day to a month depending on method and country. The merchant’s claim on that balance is itself financeable.'],
    ].map(([label,title,text]) => <article key={label}><span>{label}</span><h3>{title}</h3><p>{text}</p></article>)}</div><ul className="rh-checklist">{[
      ['The transaction has already occurred','We finance completed activity, not forecast volume.'],
      ['The obligation is established','A named counterparty owes the money, and the claim can be assigned and controlled.'],
      ['The amount is known','The sum due is fixed and reconcilable against settlement records.'],
      ['The payer is creditworthy','The obligation sits with a processor, acquirer, bank or settlement partner.'],
      ['The settlement date is predictable','The payer settles on a cycle or schedule that can be evidenced.'],
      ['The cash has not arrived yet','That gap is the only thing Rift funds.'],
    ].map(([title,text]) => <li key={title}><RiftIcon name="check" /><strong>{title}</strong><p>{text}</p></li>)}</ul><div className="rh-shift"><h3>The underwriting shift.</h3><div><p>The question is not “will this fintech survive the next year?”</p><p>It is <strong>“is this receivable genuine, who owes it, can it be assigned and controlled, when does it settle, and what is the historical failure or reversal rate?”</strong></p><Link className="r-link" to="/how-it-works">See how a facility is assessed <Arrow /></Link></div></div></div></section>
    <section className="rh-faq r-shell" id="questions"><h2>A few things<br />worth knowing.</h2><div>{[
      ['What is a receivable?','Money already owed to your business. In payments, that is usually funds held by a processor, acquirer, bank or settlement partner that are due to be released to you on a settlement cycle.'],
      ['Which receivables do you finance?','Short-term settlement receivables where the transaction has already occurred, the payer is identified, the amount is known and the settlement date is predictable. Two layers qualify: what a processor, acquirer or collection partner owes a payment company, and what a payment company owes a merchant settling through it. Customer money subject to safeguarding is not treated as freely available collateral.'],
      ['Why use USDC?','USDC can move on-chain around the clock and transfers can settle in seconds on supported networks. This speeds up the funding leg. Approval, network finality, conversion and the final local-currency payout have their own timings and depend on your own payment partners.'],
      ['Where does investor income come from?','Businesses pay interest for earlier access to funds. Investor income comes only from that borrower-paid interest as it is actually collected, after fees, expenses and losses, under each pool’s terms. Returns are not guaranteed or projected, and a receivable may be disputed, delayed, reversed or unpaid.'],
      ['How do I get started?','Send a financing enquiry with your business details and receivables, or express investment interest. An enquiry is not an offer, an allocation, an approval or a commitment; our team will follow up as products become available.'],
    ].map(([q,a]) => <details key={q}><summary>{q}<RiftIcon name="chevron" /></summary><p>{a}</p></details>)}</div></section>
    <section className="rh-close"><div className="r-shell"><h2>Keep your next<br />payment moving.</h2><div><div className="r-actions"><a className="r-button r-button-primary" href={links.financing}>Request settlement liquidity <Arrow /></a><a className="r-link" href={links.investor}>Explore investment <Arrow /></a></div><p className="rh-availability">Financing and investment products are in preparation. Enquiries are open. Capital is at risk and no return is guaranteed or projected.</p></div></div></section>
  </main><CapitalFooter /></div>;
};
