import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CapitalNav, CapitalFooter } from '../components/rift/CapitalChrome';
import { RiftIcon } from '../components/rift/RiftIcon';
import { ENQUIRY_LINKS as links } from '../lib/enquiry-config';
import '../styles/capital.scss';
import '../styles/receivables-home.scss';
const items = [
  { name: 'FX & settlement', title: 'Keep money moving.', text: 'Bridge the time between sending a payment and receiving settlement. Access dollar liquidity against verified receivables from your payment partners.', asset: 'Settlement receivables', repayment: 'Payment partner settlement', image: 'port', alt: 'Illustrative aerial photograph of an East African container port', id: 'sector-trade' },
  { name: 'Solar & PAYGo', title: 'Put more power in reach.', text: 'Turn payments from existing solar customers into capital for your next installations. Financing is assessed against eligible customer contracts and collection history.', asset: 'Existing customer payment contracts', repayment: 'Scheduled customer collections', image: 'solar', alt: 'Illustrative photograph of a solar technician inspecting a rooftop installation', id: 'sector-energy' },
  { name: 'Exports & invoices', title: 'Keep your next shipment moving.', text: 'Unlock working capital while your buyers settle their invoices. Access financing against accepted export invoices and completed deliveries.', asset: 'Accepted business invoices', repayment: 'Buyer invoice payments', image: 'export', alt: 'Illustrative photograph of a coffee quality specialist in an export warehouse', id: 'sector-agriculture' },
];
const Arrow = () => <RiftIcon name="arrow" />;
export const Home = () => {
  const [active, setActive] = useState(0);
  const item = items[active];
  function select(index: number, focus = false) { const next = (index + items.length) % items.length; setActive(next); if (focus) document.getElementById(`receivable-tab-${next}`)?.focus(); }
  return <div className="rift-site rift-home-v2"><CapitalNav /><main id="main">
    <section className="rh-hero"><div className="r-shell rh-hero-heading"><h1>Tomorrow’s payments.<br /><span>Today’s possibilities.</span></h1><div><p>Turn payments you’re owed into capital you can use. Receivables financing for businesses moving money, powering homes and trading across borders.</p><div className="r-actions"><a className="r-button r-button-primary" href={links.financing}>Explore financing <Arrow /></a><a className="r-link" href="#invest">Invest with Rift <Arrow /></a></div></div></div>
    <div className="r-shell rh-carousel" role="region" aria-roledescription="carousel" aria-label="Types of receivables"><div className="rh-tabs" role="tablist" aria-label="Explore receivables">{items.map((slide,i) => <button key={slide.name} id={`receivable-tab-${i}`} role="tab" aria-selected={active === i} aria-controls="receivable-panel" tabIndex={active === i ? 0 : -1} onClick={() => select(i)} onKeyDown={e => { if (['ArrowRight','ArrowLeft','Home','End'].includes(e.key)) { e.preventDefault(); select(e.key === 'Home' ? 0 : e.key === 'End' ? 2 : i + (e.key === 'ArrowRight' ? 1 : -1), true); } }}><span>{slide.name}</span><Arrow /></button>)}</div>
    <div className="rh-slide" id="receivable-panel" role="tabpanel" aria-labelledby={`receivable-tab-${active}`} tabIndex={0}><div className="rh-slide-photo"><img key={item.image} src={`/brand/receivables-${item.image}.png`} alt={item.alt} width="1536" height="1024" fetchPriority="high" /><div className="rh-photo-caption"><span>Capital at work</span><span>{String(active+1).padStart(2,'0')} / 03</span></div></div><div className="rh-slide-copy" aria-live="polite"><div><h2>{item.title}</h2><p>{item.text}</p></div><dl><div><dt>What backs the financing</dt><dd>{item.asset}</dd></div><div><dt>Where repayment comes from</dt><dd>{item.repayment}</dd></div></dl><div className="rh-slide-bottom"><a className="r-link" href={links.financing}>Discuss your receivables <Arrow /></a><div className="rh-controls"><button aria-label="Previous receivable" onClick={() => select(active-1)}><Arrow /></button><button aria-label="Next receivable" onClick={() => select(active+1)}><Arrow /></button></div></div></div></div><p className="rh-availability">Financing and investment products are in preparation. Enquiries are open.</p></div></section>
    <section className="rh-intro r-shell" id="vision"><h2>Good business.<br />Less waiting.</h2><div><p>Your customers need time to pay. Your business needs room to move.</p><p>Rift connects receivables with investor capital, bringing forward the money tied up in payment cycles. So businesses can settle, deliver and grow.</p><Link className="r-link" to="/how-it-works">See how Rift works <Arrow /></Link></div></section>
    <section className="rh-flow" id="how-it-works"><div className="r-shell"><div className="rh-section-heading"><h2>A clear path from<br />receivable to capital.</h2><Link className="r-link" to="/how-it-works">Explore the process <Arrow /></Link></div><div className="rh-flow-grid">{[
      ['Show what you’re owed.','Share invoices, settlement records or customer payment contracts. We assess the payer, payment history and collection terms.'],
      ['Bring your capital forward.','Agree your facility and receive an advance against eligible receivables. Put it to work where your business needs it.'],
      ['Repay as payments arrive.','Collections follow an agreed route to repay the advance and interest. A clear connection between financing and its repayment source.'],
    ].map(([title,text],i) => <article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="rh-invest r-shell" id="invest"><div><h2>Your capital.<br />Connected to<br />real business.</h2><p>Finance the payments behind everyday progress. Borrowers pay interest for earlier access to capital. That income supports investor distributions after pool charges and adjustments.</p><Link className="r-link" to="/how-it-works#investor-income">Understand how you earn <Arrow /></Link></div><div className="rh-invest-options"><article><RiftIcon name="wallet" /><h3>For individuals</h3><p>Explore Rift Wallet, your access point for future investment opportunities.</p><a className="r-link" href="https://wallet.riftfi.com">Explore the wallet <Arrow /></a></article><article><RiftIcon name="institution" /><h3>For institutions</h3><p>Discuss allocations, investment duration and the receivables that fit your mandate.</p><a className="r-link" href={links.investor}>Talk to our team <Arrow /></a></article></div></section>
    <section className="rh-sectors" id="sectors"><div className="r-shell"><div className="rh-section-heading"><h2>Different businesses.<br />A common need for capital.</h2><p>Start with the payments behind your business.</p></div><div className="rh-sector-grid">{items.map((sector,i) => <a id={sector.id} key={sector.name} href={links.financing}><img src={`/brand/receivables-${sector.image}.png`} alt={sector.alt} width="1536" height="1024" loading="lazy" /><div><h3>{sector.name}</h3><Arrow /></div><p>{i === 0 ? 'Liquidity between payment and settlement.' : i === 1 ? 'Customer collections that support your next installation.' : 'Working capital between delivery and buyer payment.'}</p></a>)}</div><div className="rh-other-sectors"><span id="sector-manufacturing">Manufacturing</span><span id="sector-mining">Resources</span><span id="sector-infrastructure">Infrastructure</span><a href={links.financing}>Have another type of receivable? Let’s talk <Arrow /></a></div></div></section>
    <section className="rh-faq r-shell" id="questions"><h2>A few things<br />worth knowing.</h2><div>{[
      ['What is a receivable?','A receivable is money owed to your business. It might be a payment awaiting settlement, an accepted invoice or payments due under an existing customer contract.'],
      ['Can solar companies finance new installations?','An eligible portfolio of existing PAYGo customer contracts can support a facility whose proceeds fund new installations. We assess collection history, contract rights, payment duration and servicing arrangements.'],
      ['Where does investor income come from?','Businesses pay interest for access to financing. Investor income comes from these payments, with distributions calculated under each pool’s terms.'],
      ['How do I get started?','Send a financing enquiry with your business details and receivables, or express investment interest. Our team will follow up as products become available.'],
    ].map(([q,a]) => <details key={q}><summary>{q}<RiftIcon name="chevron" /></summary><p>{a}</p></details>)}</div></section>
    <section className="rh-close"><div className="r-shell"><h2>Put what you’re owed<br />to work.</h2><div className="r-actions"><a className="r-button r-button-primary" href={links.financing}>Discuss financing <Arrow /></a><a className="r-link" href={links.investor}>Explore investment <Arrow /></a></div></div></section>
  </main><CapitalFooter /></div>;
};
