import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CapitalNav, CapitalFooter } from '../components/rift/CapitalChrome';
import { RiftIcon } from '../components/rift/RiftIcon';
import { FxLiquidity } from '../components/rift/FxLiquidity';
import { ENQUIRY_LINKS as links } from '../lib/enquiry-config';
import '../styles/capital.scss';
import '../styles/receivables-home.scss';
const items = [
  { name: 'Remittance companies', title: 'Keep customer payments moving.', text: 'Bring forward dollars owed by your settlement partners. Fund payouts while the incoming payment completes its settlement cycle.', asset: 'Verified settlement receivables', repayment: 'Incoming partner settlement', image: 'port', alt: 'Illustrative view of a port connecting cross-border commerce', id: 'sector-trade' },
  { name: 'Cross-border payment apps', title: 'Bridge the gap between pay-in and payout.', text: 'Access USDC financing against an established incoming payment obligation. Give your payout network liquidity before the receivable settles.', asset: 'Eligible incoming payment claims', repayment: 'Agreed settlement collections', image: 'port', alt: 'Illustrative view of international trade infrastructure', id: 'cross-border-payments' },
  { name: 'Payment service providers', title: 'Put settlement balances to work sooner.', text: 'Finance eligible receivables from processors, acquirers and settlement partners, with a clear payer, payment date and collection route.', asset: 'Verified processor and partner receivables', repayment: 'Processor or partner payment', image: 'port', alt: 'Illustrative view of a coastal trade gateway', id: 'payment-providers' },
];
const Arrow = () => <RiftIcon name="arrow" />;
export const Home = () => {
  const [active, setActive] = useState(0);
  const item = items[active];
  function select(index: number, focus = false) { const next = (index + items.length) % items.length; setActive(next); if (focus) document.getElementById(`receivable-tab-${next}`)?.focus(); }
  return <div className="rift-site rift-home-v2"><CapitalNav /><main id="main">
    <section className="rh-hero"><div className="r-shell rh-hero-heading"><h1>Dollar liquidity.<br /><span>Before settlement arrives.</span></h1><div><p>Short-term settlement financing for remittance companies, cross-border payment apps and PSPs. Access USDC against verified incoming payments and keep your payout network moving.</p><div className="r-actions"><a className="r-button r-button-primary" href={links.financing}>Request settlement liquidity <Arrow /></a><a className="r-link" href="#invest">Invest with Rift <Arrow /></a></div></div></div>
    <div className="r-shell rh-carousel" role="region" aria-roledescription="carousel" aria-label="Payment businesses we serve"><div className="rh-tabs" role="tablist" aria-label="Explore payment businesses">{items.map((slide,i) => <button key={slide.name} id={`receivable-tab-${i}`} role="tab" aria-selected={active === i} aria-controls="receivable-panel" tabIndex={active === i ? 0 : -1} onClick={() => select(i)} onKeyDown={e => { if (['ArrowRight','ArrowLeft','Home','End'].includes(e.key)) { e.preventDefault(); select(e.key === 'Home' ? 0 : e.key === 'End' ? 2 : i + (e.key === 'ArrowRight' ? 1 : -1), true); } }}><span>{slide.name}</span><Arrow /></button>)}</div>
    <div className="rh-slide" id="receivable-panel" role="tabpanel" aria-labelledby={`receivable-tab-${active}`} tabIndex={0}><div className="rh-slide-photo"><img key={item.image} src={`/brand/receivables-${item.image}.png`} alt={item.alt} width="1536" height="1024" fetchPriority="high" /><div className="rh-photo-caption"><span>Capital at work</span><span>{String(active+1).padStart(2,'0')} / 03</span></div></div><div className="rh-slide-copy" aria-live="polite"><div><h2>{item.title}</h2><p>{item.text}</p></div><dl><div><dt>What backs the financing</dt><dd>{item.asset}</dd></div><div><dt>Where repayment comes from</dt><dd>{item.repayment}</dd></div></dl><div className="rh-slide-bottom"><a className="r-link" href={links.financing}>Discuss settlement liquidity <Arrow /></a><div className="rh-controls"><button aria-label="Previous receivable" onClick={() => select(active-1)}><Arrow /></button><button aria-label="Next receivable" onClick={() => select(active+1)}><Arrow /></button></div></div></div></div><p className="rh-availability">Financing and investment products are in preparation. Enquiries are open.</p></div></section>
    <FxLiquidity />
    <section className="rh-intro r-shell" id="vision"><h2>Your customers move fast.<br />Your liquidity should too.</h2><div><p>A customer needs a payout today. Your settlement partner pays in a few days.</p><p>Rift connects dollar capital with verified short-term settlement receivables. An approved USDC advance bridges the timing gap; the incoming settlement repays the facility.</p><Link className="r-link" to="/how-it-works">See how Rift works <Arrow /></Link></div></section>
    <section className="rh-flow" id="how-it-works"><div className="r-shell"><div className="rh-section-heading"><h2>A clear path from<br />receivable to capital.</h2><Link className="r-link" to="/how-it-works">Explore the process <Arrow /></Link></div><div className="rh-flow-grid">{[
      ['Show what you’re owed.','Share your settlement records, payer and expected payment date. We verify the incoming obligation and agree collection terms.'],
      ['Bring your capital forward.','Agree your facility and receive an advance against eligible receivables. Put it to work where your business needs it.'],
      ['Repay as payments arrive.','Collections follow an agreed route to repay the advance and interest. A clear connection between financing and its repayment source.'],
    ].map(([title,text],i) => <article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="rh-invest r-shell" id="invest"><div><h2>Your capital.<br />Connected to<br />real business.</h2><p>Supply dollar liquidity to payment providers against verified settlement receivables. Providers pay a financing charge for earlier access to funds. Collected income supports investor distributions under each pool’s terms.</p><Link className="r-link" to="/how-it-works#investor-income">Understand how you earn <Arrow /></Link></div><div className="rh-invest-options"><article><RiftIcon name="wallet" /><h3>For individuals</h3><p>Explore Rift Wallet, your access point for future investment opportunities.</p><a className="r-link" href="https://wallet.riftfi.com">Explore the wallet <Arrow /></a></article><article><RiftIcon name="institution" /><h3>For institutions</h3><p>Discuss allocations, investment duration and the receivables that fit your mandate.</p><a className="r-link" href={links.investor}>Talk to our team <Arrow /></a></article></div></section>
    <section className="rh-sectors" id="sectors"><div className="r-shell"><div className="rh-section-heading"><h2>Beyond payments.<br />More possibilities ahead.</h2><p>Energy, agriculture and export finance are future opportunities. Tell us where your business needs capital.</p></div><div className="rh-sector-grid">{[
      {name:'Energy & solar',image:'solar',id:'sector-energy',text:'Register interest in future financing against eligible energy invoices and existing solar customer contracts.'},
      {name:'Agriculture & exports',image:'export',id:'sector-agriculture',text:'Register interest in future working-capital facilities against accepted buyer invoices.'},
    ].map(sector => <a id={sector.id} key={sector.name} href={links.financing}><img src={`/brand/receivables-${sector.image}.png`} alt={`Illustrative ${sector.name.toLowerCase()} sector photograph`} width="1536" height="1024" loading="lazy" /><div><h3>{sector.name}</h3><Arrow /></div><p>{sector.text}</p><span className="rh-future-cta">Express interest <Arrow /></span></a>)}</div><div className="rh-other-sectors"><span id="sector-manufacturing">Manufacturing</span><span id="sector-mining">Resources</span><span id="sector-infrastructure">Infrastructure</span><a href={links.financing}>Other financing needs? Express interest <Arrow /></a></div></div></section>
    <section className="rh-faq r-shell" id="questions"><h2>A few things<br />worth knowing.</h2><div>{[
      ['What is a receivable?','A receivable is money owed to your business. It might be a payment awaiting settlement, an accepted invoice or payments due under an existing customer contract.'],
      ['Why use USDC?','USDC can move onchain around the clock and transfers can settle in seconds on supported networks. This speeds up the funding leg. Approval, network finality, conversion and final customer payout have their own timings.'],
      ['Where does investor income come from?','Businesses pay interest for access to financing. Investor income comes from these payments, with distributions calculated under each pool’s terms.'],
      ['How do I get started?','Send a financing enquiry with your business details and receivables, or express investment interest. Our team will follow up as products become available.'],
    ].map(([q,a]) => <details key={q}><summary>{q}<RiftIcon name="chevron" /></summary><p>{a}</p></details>)}</div></section>
    <section className="rh-close"><div className="r-shell"><h2>Keep your next<br />payment moving.</h2><div className="r-actions"><a className="r-button r-button-primary" href={links.financing}>Request settlement liquidity <Arrow /></a><a className="r-link" href={links.investor}>Explore investment <Arrow /></a></div></div></section>
  </main><CapitalFooter /></div>;
};
